modified abci-user-manual for portal
aistabci/abci-docs pull request #471
Opened 2024-05-01 07:55 UTC by ABCI-FJSE

2024年度向けの利用者ポータル利用手引きの修正を行いました。
ご確認のほどよろしくお願いします。

なお、以下記述については修正しておりませんが、記述内容を残すか等についてご検討のほどよろしくお願いします。

- 「2.1.2. 初回ログイン」のNote内「共同研究等に基づくABCI利用の流れは下記URLにて参照可能です。」
→共同研究等...の規約約款のリンクは規定への同意の画面から消しておりますが、記述を削除すべきでしょうか。
- 「3.5.2. グループディスク追加または削減申請」のNote内の文章
「追加容量に応じた申請月度から年度末までの ABCI ポイントが消費されます。」
「削減容量に応じた申請翌月度から年度末までの ABCI ポイントが返却されます。」
→文中の「年度末までの」が実際は「10月まで(10/31)」で計算されますが、記述内容を修正すべきでしょうか。

2024-05-01 11:02 UTC, ttakayuki commented
すみません、簡単なものでよいので、変更した画像について「何を/どこ」を「どう変更したのか」の説明をお願いします。
英語版、日本語版で修正箇所は同じでしょうから、どちらかの版でかまいませんので。

2024-05-02 00:29 UTC, u-kawasaki approved these changes
キャプチャ画面・リンク先の更新を確認しました。

2024-05-02 02:45 UTC, ABCI-FJSE commented
戸澤様
ご依頼のありました、画像の修正箇所について以下に示します。
redmine18495(redmine18492)の画面改修に対応した画像の差し替えとなります。

- 1_01_A.png:
規約廃止・約款へ統一、リンク他改定施行日変更の対応

- 1_02_A.png:
社印押印省略についてコメント

- 1_03_A.png:
利用期間、ABCIポイント数のコメント

- 1_04_A.png:
国外所属機関→居住者/非居住者
分類(規約廃止・約款へ統一)
通信欄(見積書のリンク)
請求書送付先(請求書発行期日、回答書押印希望)※削除

- 1_05_B.png:
国外所属機関→居住者/非居住者

- 1_05_F.png:
居住者/非居住者についてコメント・リンク

- 1_06_A.png:
国外所属機関→居住者/非居住者
請求書送付先(請求書発行期日、回答書押印希望)※削除

- 2_01_F.png:
規約廃止・約款へ統一、リンク他改定施行日変更の対応

- 2_08_C.png:
改定施行日変更の対応

- 3_04_B.png:
ABCIポイント数のコメント

- 3_04_D.png:
ABCIポイント数のコメント

- 3_04_I.png:
国外所属機関→居住者/非居住者

- 3_04_M.png:
居住者/非居住者についてコメント・リンク

- 3_04_P.png:
国外所属機関→居住者/非居住者

- 3_04_V.png:
国外所属機関→居住者/非居住者
分類(規約廃止・約款へ統一)
通信欄(見積書のリンク)
請求書送付先(請求書発行期日、回答書押印希望)※削除

- 3_05_B.png:
国外所属機関→居住者/非居住者

- 3_05_E.png:
国外所属機関→居住者/非居住者

- 3_05_F.png:
分類(規約廃止・約款へ統一)
通信欄(見積書のリンク)

- 3_06_B.png:
改定施行日変更の対応

- 3_06_D_1.png:
改定施行日変更の対応

2024-05-07 08:30 UTC, ttakayuki approved these changes
> ご依頼のありました、画像の修正箇所について以下に示します。

ありがとうございます。内容について確認しました。

2024-05-08 00:25 UTC, s-yama requested changes
今回の修正箇所ではなくて恐縮ですが、下記を変更お願いします。

* 修正前：
共同研究等に基づくABCI利用の流れは下記URLにて参照可能です。
https://abci.ai/ja/how_to_use/

修正後：
共同研究等に基づくABCI利用については下記URLにて参照可能です。
https://abci.ai/ja/link/download_etc.html

2024-05-10 03:00 UTC, ABCI-FJSE commented
山本様
ご依頼いただいた箇所の修正を実施しましたので、ご確認のほどよろしくお願いいたします。

2024-05-10 04:02 UTC, s-yama approved these changes
修正ありがとうございました。
この内容でOKです。

2024-05-15 07:21 UTC, merged