mod strage capacity
aistabci/abci-docs pull request #494
Opened 2024-10-02 00:27 UTC by ABCI-FJSE

以下チケットに関連した利用手引きのストレージ容量の修正を実施しました。
https://aist-rp-ith.cloud.redmine.jp/issues/19737
ご確認のほどよろしくお願いします。

2024-10-02 01:05 UTC, T-NIITSUMA-PROG requested changes
グローバルスクラッチ領域　/scratch が抜けております。（0.1PB）
こちらを加算すると、総容量：24.7PBになります。

2024-10-02 04:45 UTC, s-yama commented on en/docs/system-overview.md
> +The ABCI system has five storage systems for storing large amounts of data used for AI and Big Data applications, and these are used to provide shared file systems and ABCI Cloud Storage. The total e
24.6 PB を　24.7 PB に修正お願いします。

2024-10-02 04:46 UTC, s-yama commented on ja/docs/system-overview.md
> +ABCIシステムは、人工知能やビッグデータ応用に用いる大容量データを格納するためのストレージシステムを5基備えており、これらを用いて共有ファイルシステム及びABCIクラウドストレージを提供しています。合算で最大24.6 PBの実効容量があります。
24.6 PB を　24.7 PB に修正お願いします。

2024-10-02 05:24 UTC, ABCI-FJSE commented
グローバルスクラッチ領域 /scratch (0.1PB) の実体は /bb領域配下に /bb/scratch ディレクトリとして存在しています。
容量としては /bb 領域に含まれますので /scratch (0.1PB) は合計に含めておりません。

2024-10-02 07:35 UTC, ABCI-FJSE commented
/scratchの容量のところに物理的には/bbに含まれる旨を記載いたしました。
ご確認のほどよろしくお願いいたします。

2024-10-03 01:12 UTC, T-NIITSUMA-PROG approved these changes

2024-10-03 01:16 UTC, s-yama approved these changes

2024-10-03 01:45 UTC, ttakayuki reviewed
ストレージシステムの個数が更新されていないように思いますので、こちらの修正もお願いできますでしょうか。

2024-10-03 01:45 UTC, ttakayuki commented on ja/docs/system-overview.md
> +ABCIシステムは、人工知能やビッグデータ応用に用いる大容量データを格納するためのストレージシステムを5基備えており、これらを用いて共有ファイルシステム及びABCIクラウドストレージを提供しています。合算で最大24.6 PBの実効容量があります。
> 格納するためのストレージシステムを5基備えており

projects、scratch分が減り現在は4基だと思いますのでこちらの修正もお願いします(表とも合いませんし)。

2024-10-03 01:45 UTC, ttakayuki commented on en/docs/system-overview.md
> +The ABCI system has five storage systems for storing large amounts of data used for AI and Big Data applications, and these are used to provide shared file systems and ABCI Cloud Storage. The total e
> The ABCI system has five storage systems

日本語版と同様、こちらも修正をお願いします。

2024-10-03 07:22 UTC, ABCI-FJSE commented on ja/docs/system-overview.md
> +ABCIシステムは、人工知能やビッグデータ応用に用いる大容量データを格納するためのストレージシステムを5基備えており、これらを用いて共有ファイルシステム及びABCIクラウドストレージを提供しています。合算で最大24.6 PBの実効容量があります。
4基に修正いたしました。ご確認のほどよろしくお願いいたします。

2024-10-03 07:22 UTC, ABCI-FJSE commented on en/docs/system-overview.md
> +The ABCI system has five storage systems for storing large amounts of data used for AI and Big Data applications, and these are used to provide shared file systems and ABCI Cloud Storage. The total e
修正いたしました。ご確認のほどよろしくお願いいたします。

2024-10-03 07:52 UTC, ttakayuki commented on ja/docs/system-overview.md
> +ABCIシステムは、人工知能やビッグデータ応用に用いる大容量データを格納するためのストレージシステムを5基備えており、これらを用いて共有ファイルシステム及びABCIクラウドストレージを提供しています。合算で最大24.6 PBの実効容量があります。
ありがとうございます。修正を確認しました。

2024-10-03 07:53 UTC, ttakayuki commented on en/docs/system-overview.md
> +The ABCI system has five storage systems for storing large amounts of data used for AI and Big Data applications, and these are used to provide shared file systems and ABCI Cloud Storage. The total e
こちらも修正を確認しました。

2024-10-03 07:54 UTC, merged