mod system-updates
aistabci/abci-docs pull request #495
Opened 2024-10-25 01:27 UTC by ABCI-FJSE

以下チケットでご依頼のありました、利用手引きの修正を実施いたしました。
ご確認いただき、コメント等ございましたらよろしくお願いします。
https://aist-rp-ith.cloud.redmine.jp/issues/19791

2024-10-25 02:30 UTC, s-yama commented on ja/docs/system-updates.md
> +    * ABCIポイント使用履歴
ABCIポイント使用履歴 の参照については、機能を提供いただきたく、この行を削除お願いできませんでしょうか。

2024-10-25 03:09 UTC, T-NIITSUMA-PROG requested changes
不要な、がついてしまっています。

確認をお願いします。

2024-10-25 03:09 UTC, T-NIITSUMA-PROG commented on ja/docs/system-updates.md
> +、
不要な、がついてしまっています。

2024-10-25 04:22 UTC, ABCI-FJSE commented on ja/docs/system-updates.md
> +    * ABCIポイント使用履歴
ご指摘の行を削除しました。

2024-10-25 04:22 UTC, ABCI-FJSE commented on ja/docs/system-updates.md
> +、
ご指摘ありがとうございます。、を削除しました。

2024-10-25 07:21 UTC, s-yama approved these changes
私はこれで良いと思います。

2024-10-25 07:22 UTC, s-yama commented on ja/docs/system-updates.md
> +    * ABCIポイント使用履歴
ありがとうございます。確認しました。

2024-10-25 08:29 UTC, T-NIITSUMA-PROG commented on ja/docs/system-updates.md
> +、
修正ありがとうございました

2024-10-25 08:30 UTC, T-NIITSUMA-PROG approved these changes

2024-10-25 09:16 UTC, ttakayuki commented
構成や文言など変更点が多いのでこちらでリライトしました。
リライトしたものを添付しますのでこちらでは如何がでしょうか。> 山本様

修正点:
1. 構成を整理しました。
    * "2024-11中旬頃"の中に12月の更新予定が入っているのを分けました。
2. あやふやな文言を整理しました。
    * "中旬頃"、"予定"、"日程調整中" はまとめて"予定"としました。
3. 指示代名詞をなるべく削除/修正しました。
4. `ABCI 3.0 /home がマウントされます`だと、2.0の/homeを潰すように読めますが違いますよね?
5. 「利用者ポータルの制限」中、箇条書きの項目をポータルガイドのタイトルに合わせました。

リライトしたsystem-update.md(日本語版)を添付します。
[system-updates.md](https://github.com/user-attachments/files/17519612/system-updates.md)

2024-10-29 23:50 UTC, s-yama approved these changes
修正ありがとうございました。私はこれで良いと思います。

2024-10-30 00:34 UTC, T-NIITSUMA-PROG approved these changes
戸澤さんの内容で問題ないと思います。

2024-10-30 02:54 UTC, ttakayuki commented
英語版(en-system-update.md)を用意しました。
日本語版(ja-system-update.md)もいくつか抜け(アンカーなど)がありましたので修正しています。
問題なければこちらに差し替えていただけますでしょうか。
[en-system-updates.md](https://github.com/user-attachments/files/17565376/en-system-updates.md)
[ja-system-updates.md](https://github.com/user-attachments/files/17565377/ja-system-updates.md)

2024-10-30 03:26 UTC, ABCI-FJSE commented
戸澤様修正について取り込みを実施しました。ご確認のほどよろしくお願いします。

2024-10-30 03:47 UTC, ttakayuki approved these changes
対応ありがとうございます。変更されていることを確認しました。

2024-10-30 04:02 UTC, merged