Add v3 document
aistabci/abci-docs pull request #500
Opened 2024-11-13 09:07 UTC by m-yamanashi

ABCI 3.0 利用手引き第一版に関するドキュメントを追加するPRです。

2024-11-14 03:31 UTC, s-yama commented on v3/ja/docs/getting-started.md
> +* SSH公開鍵の登録については、運用担当者までご連絡ください。
下記の修正をお願いします。
* 修正前： SSH公開鍵の登録については、運用担当者までご連絡ください。
* 修正後： SSH公開鍵の登録については、運用担当者（abci3-qa@abci.ai ）までご連絡ください。

2024-11-14 03:39 UTC, s-yama commented on v3/ja/docs/job-execution.md
> +| rt\_HG | ノード共有<br>GPU利用 | 8 | 1 | 144 | 1.4 | 2|
ＨＧの資源タイプ課金係数は2ではなく3です。修正お願いします。
* 修正前：| rt\_HG | ノード共有<br>GPU利用 | 8 | 1 | 144 | 1.4 | 2|
* 修正後：| rt\_HG | ノード共有<br>GPU利用 | 8 | 1 | 144 | 1.4 | 3|

2024-11-14 03:47 UTC, s-yama commented on v3/ja/docs/job-execution.md
> +| rt_HF | 736 |
11月には766ノード存在しないため、HFは736稼働は出来ないと思います。ノード割当以外で、バッチジョブでHFを実行可能なノード個数はいくつになるでしょうか？

2024-11-14 03:56 UTC, s-yama commented on v3/ja/docs/system-overview.md
> +ABCIシステムは、合計6,128基のNVIDIA H200 GPUアクセラレーターを備えた766台の計算ノードを始めとする計算リソース、合算で約74PBの容量を有する共有ファイルシステム及びABCIクラウドストレージ、これらを高速に結合するInfiniBandネットワーク、ファイアウォールなどからなるハードウェアと、これらを最大限活用するためのソフトウェアから構成されます。また、ABCIシステ
下記を修正お願いします。
* SINET5
* SINET6

2024-11-14 05:18 UTC, ttakayuki reviewed
ひとまず目についた箇所についてコメントします。
ご確認および修正をお願いします。

2024-11-14 05:31 UTC, s-yama commented on v3/ja/docs/job-execution.md
> +### Reservedサービス {#reserved-service}
11月に利用可能な予約機能は、何でしょうか？
11月に利用可能な機能でない場合は、「1月中旬から利用可能です」と記載お願いします。

2024-11-14 05:56 UTC, T-NIITSUMA-PROG requested changes
全般、[qa@abci.ai]を[abci3-qa@abci.ai]確認、修正をお願いします。

2024-11-14 05:56 UTC, T-NIITSUMA-PROG commented on v3/ja/docs/job-execution.md
> +* 予約期間中に計算ノードが利用不可となった場合などの時は、[お問い合わせ](./contact.md)のページをご覧の上、<qa@abci.ai> までご連絡ください。
お問合わせにリンクが飛ばない。

qa@abci.aiをabci3-qa@abci.aiｎ変更願います。

2024-11-15 07:38 UTC, s-yama commented on v3/ja/docs/job-execution.md
> +| -l *resource_type* | 予約する資源タイプを*resource_type*で指定します。 省略した場合は、rt_F が指定されたとみなします。|
下記を修正お願いします。
* 修正前： rt_F
* 修正後： rt_FH

2024-11-15 07:40 UTC, s-yama commented on v3/ja/docs/job-execution.md
> +
qsubコマンドで`-l select=1:ncpus=1`を指定してもCPU数は最大値が設定される。
　(CPU数の指定が有効でないのに、CPU数の指定が必須という仕様はユーザから指摘を受ける恐れがある。)

これは既知の問題ですか？11/18までに、修正できないのであれば、「既知の問題」という章を作って「問題」として、掲載ください。

参考情報
ABCI 2.0 の「既知の問題」
https://docs.abci.ai/ja/known-issues/

2024-11-15 08:05 UTC, s-yama commented on v3/ja/docs/job-execution.md
> +## 事前予約（更新中） {#advance-reservation}
11月～12月のEarly Acces者に割り当てられたノードの使い方の手順を、利用の手引きのどこかに記載ください。
この「事前予約（更新中）」の「予約」機能で、使えるのですか？　

2024-11-15 08:12 UTC, m-yamanashi commented on v3/ja/docs/getting-started.md
> +* SSH公開鍵の登録については、運用担当者までご連絡ください。
頂いたコメントについて、修正致しました。

2024-11-15 08:13 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +| rt\_HG | ノード共有<br>GPU利用 | 8 | 1 | 144 | 1.4 | 2|
頂いたコメントについて、修正致しました。

2024-11-15 08:13 UTC, m-yamanashi commented on v3/ja/docs/system-overview.md
> +ABCIシステムは、合計6,128基のNVIDIA H200 GPUアクセラレーターを備えた766台の計算ノードを始めとする計算リソース、合算で約74PBの容量を有する共有ファイルシステム及びABCIクラウドストレージ、これらを高速に結合するInfiniBandネットワーク、ファイアウォールなどからなるハードウェアと、これらを最大限活用するためのソフトウェアから構成されます。また、ABCIシステ
頂いたコメントについて、修正致しました。

2024-11-15 08:13 UTC, m-yamanashi commented on v3/ja/mkdocs.yml
> +        '03.md': 'job-execution.md'
不要となりますため、削除致しました。

2024-11-15 08:14 UTC, m-yamanashi commented on v3/ja/docs/system-overview.md
> +ABCIシステムは、人工知能やビッグデータ応用に用いる大容量データを格納するためのストレージシステムを3基備えており、これらを用いて共有ファイルシステム及びABCIクラウドストレージを提供しています。合算で最大約74 PBの実効容量があります。
コメント頂いた文言について、削除致しました。

2024-11-15 08:14 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +* 予約期間中に計算ノードが利用不可となった場合などの時は、[お問い合わせ](./contact.md)のページをご覧の上、<qa@abci.ai> までご連絡ください。
qa@abci.aiをabci3-qa@abci.aiに修正致しました。リンク先の修正について、お手数をおかけいたしますが、今しばらくお待ちください。

2024-11-15 08:14 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +| -l *resource_type* | 予約する資源タイプを*resource_type*で指定します。 省略した場合は、rt_F が指定されたとみなします。|
頂いたコメントについて、修正致しました。

2024-11-15 08:28 UTC, ttakayuki commented on v3/ja/mkdocs.yml
> +        '03.md': 'job-execution.md'
ありがとうございます。こちらについては削除されていることを確認しました。

2024-11-15 08:31 UTC, ttakayuki commented on v3/ja/docs/system-overview.md
> +ABCIシステムは、人工知能やビッグデータ応用に用いる大容量データを格納するためのストレージシステムを3基備えており、これらを用いて共有ファイルシステム及びABCIクラウドストレージを提供しています。合算で最大約74 PBの実効容量があります。
確認しましたが、こちらは削除されていませんでした。コミットの確認をお願いします。

2024-11-15 08:54 UTC, ttakayuki commented on v3/ja/docs/system-overview.md
> +ABCIシステムは、人工知能やビッグデータ応用に用いる大容量データを格納するためのストレージシステムを3基備えており、これらを用いて共有ファイルシステム及びABCIクラウドストレージを提供しています。合算で最大約74 PBの実効容量があります。
修正を確認しました。

2024-11-15 08:55 UTC, ttakayuki commented
@m-yamanashi 
Pull Requestとは直接関係ないのですが、作業PC上のgit環境において、ユーザー名とメールアドレスは正しい値を設定してください。
git logコマンドのAuthorフィールドがおかしな値になっています。

2024-11-15 11:20 UTC, m-yamanashi commented
> @m-yamanashi Pull Requestとは直接関係ないのですが、作業PC上のgit環境において、ユーザー名とメールアドレスは正しい値を設定してください。 git logコマンドのAuthorフィールドがおかしな値になっています。
失礼いたしました。ユーザ名とメールアドレスを正しく設定させて頂きました。

2024-11-15 11:45 UTC, m-yamanashi commented on v3/ja/docs/system-overview.md
> +| ABCIクラウドストレージ | /groups_s3 | 1 PB | Lustre |  |
名前をオブジェクト領域に変更致しました。

2024-11-15 11:49 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +| rt_HF | 736 |
今回解放する計算ノードが108台となり、そのうち88台はグループに割り当てられていますので、残りの20台がバッチジョブで利用可能となります。

2024-11-15 11:59 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +## 事前予約（更新中） {#advance-reservation}
インタラクティブジョブ、バッチジョブ記載の手順両方に置いて、各グループは割り当てられたノードにてジョブが実行されます。このため事前に予約を行う必要はございません。

2024-11-18 02:15 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +### Reservedサービス {#reserved-service}
「1月中旬から利用可能です」と追記致しました。

2024-11-18 02:26 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +
CPU数の指定が必須という仕様を変更し、CPU数を指定しないでもジョブが実行できるよう変更致しました。
このため、利用手引きのジョブオプションの記載についても以下の通り変更しています。

> | -l select=*num*[*:ncpus=num_cpus:mpiprocs=num_mpi:ompthreads=num_omp*] | ノード数を*num*で、資源タイプに対応したCPU数を*num_cpus*で、MPIプロセス数を*num_mpi*で、スレッド数を*num_omp*で指定します。本オプションは指定必須です。 |

2024-11-18 02:46 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +* 予約期間中に計算ノードが利用不可となった場合などの時は、[お問い合わせ](./contact.md)のページをご覧の上、<qa@abci.ai> までご連絡ください。
contact.mdを追加し、リンクに問題無く飛べることを確認致しました。

2024-11-18 04:20 UTC, s-yama approved these changes

2024-11-18 04:24 UTC, merged