mod about services
aistabci/abci-docs pull request #503
Opened 2024-11-19 01:28 UTC by ABCI-FJSE

山本様
以下のredmineチケットでご依頼のありました利用手引きについて修正を実施いたしました。
ご確認のほどよろしくお願いします。
https://aist-rp-ith.cloud.redmine.jp/issues/19791#note-13

2024-11-19 04:23 UTC, ttakayuki requested changes
追記していただいた終了のお知らせですが、ページの一番上、タイトルヘッダー(`#` 1つだけ)より上に置いた方がわかりやすいように思います。
また、admonitionのラベルをnoteからinfoに変更していただけますでしょうか。

なお、mpi.md、gpu.md、apps/index.mdのadmonitionからは日付を省いています。

2024-11-19 04:23 UTC, ttakayuki commented on ja/docs/mpi.md
> +
文体を合わせた方がわかりやすいように思います。
```
!!! info
    計算ノードのサービス終了にともない、MPIは使用できません。
```

2024-11-19 04:23 UTC, ttakayuki commented on ja/docs/storage.md
>  * [ABCIクラウドストレージ](abci-cloudstorage.md)
グローバルスクラッチ領域のサービスも終了したと思いますので削除をお願いします。
また、「ABCIで利用可能なストレージは、下記の5種類です。」の数字の変更もお願いします。 

```
ABCIで利用可能なストレージは、下記の3種類です。
```

今回の修正と関係なく恐縮ですが。
264行めの「メモリインテンシブノードのサービスは、...終了しました」のadmonitionを削除して、ページトップに今回終了したサービスと合わせてアナウンスを書いていただけないでしょうか。

```
!!! info
    * 2023年10月27日15:00をもって、メモリインテンシブノードサービスは終了しました。
    * 2024年10月31日をもって、[グローバルスクラッチ領域](#scratch-area)、[ローカルストレージ](#local-storage)サービスは終了しました。

 # ストレージ
```

2024-11-19 04:23 UTC, ttakayuki commented on ja/docs/storage.md
> +
文体を合わせた方がわかりやすいように思います。
```
!!! info
    2024年10月31日をもって、ローカルストレージサービスは終了しました。
```

また、`## グローバルスクラッチ領域 {#scratch-area}` の下にもinfoを追加していただけますでしょうか。

```
!!! info
    2024年10月31日をもって、グローバルスクラッチ領域サービスは終了しました。
```

2024-11-19 04:23 UTC, ttakayuki commented on ja/docs/system-overview.md
> +
文体を合わせた方がわかりやすいように思います。
```
!!! info
    2024年10月31日をもって、[計算ノード(V)](#compute-node-v)および[計算ノード(A)](#compute-node-a)のサービスは終了しました。
```

2024-11-19 07:38 UTC, ABCI-FJSE commented on ja/docs/apps/index.md
> +
ご指摘の箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2024-11-19 07:38 UTC, ABCI-FJSE commented on ja/docs/gpu.md
> +
ご指摘の箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2024-11-19 07:38 UTC, ABCI-FJSE commented on ja/docs/job-execution.md
> +
ご指摘の箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2024-11-19 07:38 UTC, ABCI-FJSE commented on ja/docs/mpi.md
> +
ご指摘の箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2024-11-19 07:39 UTC, ABCI-FJSE commented on ja/docs/storage.md
>  * [ABCIクラウドストレージ](abci-cloudstorage.md)
ご指摘の箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2024-11-19 07:39 UTC, ABCI-FJSE commented on ja/docs/storage.md
> +
ご指摘の箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2024-11-19 07:39 UTC, ABCI-FJSE commented on ja/docs/system-overview.md
> +
ご指摘の箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2024-11-19 07:51 UTC, ttakayuki commented on ja/docs/gpu.md
> +
修正を確認しました。

2024-11-19 07:51 UTC, ttakayuki commented on ja/docs/job-execution.md
> +
修正を確認しました。

2024-11-19 07:51 UTC, ttakayuki commented on ja/docs/mpi.md
> +
修正を確認しました。

2024-11-19 07:52 UTC, ttakayuki commented on ja/docs/storage.md
>  * [ABCIクラウドストレージ](abci-cloudstorage.md)
ありがとうございます。修正を確認しました。

2024-11-19 07:52 UTC, ttakayuki commented on ja/docs/system-overview.md
> +
修正を確認しました。

2024-11-19 07:52 UTC, ttakayuki approved these changes

2024-11-19 07:53 UTC, ttakayuki commented on ja/docs/storage.md
> +
修正を確認しました。

2024-11-20 02:55 UTC, T-NIITSUMA-PROG approved these changes

2024-11-25 02:22 UTC, s-yama approved these changes

2024-11-25 02:22 UTC, merged