Service charge coefficient is updated
aistabci/abci-docs pull request #504
Opened 2024-11-19 05:41 UTC by m-yamanashi

サービス課金係数を更新するためのPRです。

2024-11-19 07:31 UTC, ttakayuki approved these changes

2024-11-22 10:39 UTC, ttakayuki requested changes
修正ありがとうございます。コメントしますのでご確認ください。

2024-11-22 10:39 UTC, ttakayuki commented on v3/ja/docs/job-execution.md
> +[username@int1 ~]$ qsub -I -P grpname -q rt_HF -l select=1
ncpusの削除ですが、続くバッチジョブのサンプルにも2箇所残っているため、そちらの削除もお願いします。

2024-11-25 01:39 UTC, m-yamanashi commented on v3/ja/docs/job-execution.md
> +[username@int1 ~]$ qsub -I -P grpname -q rt_HF -l select=1
残っていたncpusの記載について、削除致しました。

2024-11-25 02:10 UTC, s-yama commented on v3/ja/docs/system-overview.md
>  | ABCIオブジェクト領域 | /groups_s3 | 1 PB | Lustre |  |
山梨さん
修正が終わったら、連絡ください。
※この修正が終わったら、approve, merge, publishへ進みたいと考えています。

2024-11-25 02:27 UTC, m-yamanashi commented on v3/ja/docs/system-overview.md
>  | ABCIオブジェクト領域 | /groups_s3 | 1 PB | Lustre |  |
コメント頂いておりました点について、修正致しました。

2024-11-25 02:28 UTC, s-yama approved these changes

2024-11-25 02:28 UTC, T-NIITSUMA-PROG approved these changes

2024-11-25 03:06 UTC, ttakayuki commented on v3/ja/docs/job-execution.md
> +[username@int1 ~]$ qsub -I -P grpname -q rt_HF -l select=1
ありがとうございます。修正を確認しました。

2024-11-25 03:06 UTC, ttakayuki commented on v3/ja/docs/system-overview.md
>  | ABCIオブジェクト領域 | /groups_s3 | 1 PB | Lustre |  |
修正を確認しました。

2024-11-25 07:07 UTC, merged